version : '3'

services:
  database:
    image: postgres:latest
    container_name: 'database'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
 
  backend:
    build : .
    command: bash -c "python manage.py makemigrations aniresfr && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name : 'backend'
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
