# Generated by Django 5.0.1 on 2024-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('animal_type', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('landmark', models.CharField(max_length=200)),
            ],
        ),
    ]
