# Generated by Django 5.0.3 on 2024-05-16 15:29

import aniresfr.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_ngo', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('notify_token', models.CharField(default='', max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=15)),
                ('animal_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('numberOfAnimals', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('landmark', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('reported_time', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.DateTimeField(default=aniresfr.models.one_day_from_now)),
                ('assigned_to', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('ngo_name', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('tags', models.JSONField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('application_deadline', models.DateTimeField()),
                ('age_group', models.IntegerField()),
                ('image_link', models.URLField(blank=True, null=True)),
                ('is_over', models.BooleanField(default=False)),
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_list', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('no_reports', models.IntegerField(default=0)),
                ('applied_campaigns', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('level', models.IntegerField(default=1)),
                ('coins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NgoUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('emergency_contact_number', models.CharField(default='', max_length=15)),
                ('animals_supported', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('website', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=500)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('no_received_reports', models.IntegerField(default=0)),
                ('created_campaigns_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
            ],
        ),
    ]
