# Generated by Django 4.2.9 on 2024-02-27 17:38

import aniresfr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniresfr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('ngo_name', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('tags', models.JSONField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('application_deadline', models.DateTimeField()),
                ('age_group', models.IntegerField()),
                ('image_link', models.URLField(blank=True, null=True)),
                ('is_over', models.BooleanField(default=False)),
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_list', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='timestamp',
            new_name='reported_time',
        ),
        migrations.AddField(
            model_name='animal',
            name='assigned_to',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='animal',
            name='response_time',
            field=models.DateTimeField(default=aniresfr.models.one_day_from_now),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='emergency_contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
