# Generated by Django 5.0.3 on 2024-05-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniresfr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='profile_image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
