# Generated by Django 4.2.9 on 2024-01-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniresfr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='phone_number',
            new_name='user_phone',
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='user_email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='user_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='condition',
            field=models.CharField(max_length=50),
        ),
    ]
