# Generated by Django 4.2.9 on 2024-01-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniresfr', '0002_rename_name_animal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='address',
            field=models.CharField(default=" ", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='numberOfAnimals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
