# Generated by Django 4.2.9 on 2024-02-27 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniresfr', '0002_campaign_rename_timestamp_animal_reported_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='applied_campaigns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
