# Generated by Django 4.2.9 on 2024-01-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniresfr', '0003_animal_address_animal_numberofanimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='numberOfAnimals',
            field=models.CharField(max_length=15),
        ),
    ]
