# Generated by Django 4.2.9 on 2024-02-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniresfr', '0003_customuser_applied_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='no_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ngouser',
            name='no_received_reports',
            field=models.IntegerField(default=0),
        ),
    ]
