# Generated by Django 5.0.3 on 2024-03-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniresfr', '0005_ngouser_created_campaigns_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='notify_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
